### PR TITLE
Something tracker

### PR DESCRIPTION
**Pull request by gr2m**
the original `my-first-hoodie` is [over 3 years old](https://github.com/hoodiehq/my-first-hoodie/commit/609ba5d5e0bb9c71aabc84f3913a68cc05b1b03d). Wow, time flies.

With a new Hoodie release around the corner, it’s time for something new.
### :bulb: Idea: Something Tracker

We would like to build the most simple tracking app imaginable. Track a number with a note, without telling if it’s time, expenses, or whatever. It’s the “Something Tracker”.
### Motivation
- People understand immediately what they can do, there is only one thing to do :)
- Learn like it’s the 90s: right-click, view page source
- when creating a new app, my-first-hoodie gets setup by default. So the app should be great to extend it with own ideas. It will be easy to extend “Something Tracker” to a tracker for expenses, time, inventory
- the app will also be a simple enough to show how to use React, Ember, <you name it> with Hoodie, the adjustments will be easy
- we hope for a ton of hands-on tutorials on how to do the above two things :)
### Features
- responsive design
- add a line with a number and a note
- edit an existing line
- remove an existing line
- sign up / sign in / sign out
### Help :)

The app is only an `index.html`, an empty `app.css` and a few lines in `app.js`. We can use the [store API](https://github.com/hoodiehq/hoodie-client-store#api) as it doesn't need any backend.

We’d love to have some fine people helping us making this great <3
### Preview

The current state can be seen here:

https://rawgit.com/hoodiehq/my-first-hoodie/something-tracker/www/index.html

### CODE REVIEW

**Comment by ianstalter123** [comment]
@gr2m whats the process for working on this?
Also how do I run locally and test it - I tried cloning the repo, npm install and npm start but hoodie won't start.
Also I noticed on your preview link that login throws an error and a few other issues (for example if you try to add 2 items with the same name shouldn't they combine?)

**Comment by gr2m** [comment]
Hey @ianstalter123, try to follow these steps to install it locally:
https://github.com/hoodiehq/my-first-hoodie/tree/something-tracker#local-setup-to-test-new-hoodie

Does that work for you?

**Comment by Guria** [comment]
@ianstalter123 preview have no backend at all.

@gr2m got app running. But store doesn't syncs with server. Does it supposed it to sync at current state?

**Comment by gr2m** [comment]
@Guria as of now, we only test the flow sign up - sign in - sync. We don’t yet test sign in to an existing account without sign up beforehand.

If you like, add a failing test, and we look into it together?

**Comment by ianstalter123** [comment]
@gr2m 
I followed the steps you mentioned and I can view the couchdb url in my browser with admin:secret,
but running: npm start -- --dbUrl=http://admin:secret@localhost:5984
I get: 
Error: Could not find CouchDB at http://admin:secret@localhost:5984

**Comment by gr2m** [comment]
@ianstalter123 you must start CouchDB yourself: http://couchdb.apache.org/ You should be able open the CouchDB Admin UI at http://localhost:5984/_utils, and there you can create an admin account with username "admin" and password "secret". After that you should be able to start the app with `npm start -- --dbUrl=http://admin:secret@localhost:5984`

**Comment by ianstalter123** [comment]
@gr2m I created an admin account like: 
sudo curl -X PUT http://localhost:5984/_config/admins/admin -d '"secret"'  
and it is showing that it exists but still not connecting for me with hoodie, maybe I need to reinstall couchdb

**Comment by gr2m** [comment]
@ianstalter123 check the couchdb logs. You can also increase Hoodie’s log level by appending `--loglevel=silly`. Can you tell your versions of CouchDB, Node, NPM,

**Comment by ianstalter123** [comment]
@gr2m 
couchdb 1.6.1
node v5.2.0
npm 3.3.12

**Comment by ianstalter123** [comment]
@gr2m now getting error (after creating admin account) Error: Could not retrieve CouchDB secret

**Comment by NickColley** [comment]
@ianstalter123 can you try going to http://localhost:5984/_utils and seeing in the bottom right if an admin account has been created?

**Comment by ianstalter123** [comment]
@nickcolley  -- haha yeah that fixed it thanks (created a new user there after logging in with admin), I was creating user from command line which was probably causing the issue, didn't see the login link -- I'm going to try to make a react version of the something tracker here maybe will add into a pull request or something

**Comment by gr2m** [comment]
@ianstalter123 

> Error: Could not retrieve CouchDB secret

I run into this exact issue the other day and had to fix it for travis:
https://github.com/hoodiehq/my-first-hoodie/commit/e8a950e7da584d9df87ef5b61972543e39a44c8a#diff-354f30a63fb0907d4ad57269548329e3R19

If you create a user from command line and quickly after start Hoodie, there might be a timing issue with CouchDB. We should work around that in Hoodie (server) itself

**Comment by Guria** [comment]
> @gr2m now getting error (after creating admin account) Error: Could not retrieve CouchDB secret

you have to edit your couchdb config to add record like

```
[couch_httpd_auth]
secret = yours3cr37pr4s3
```

http://guide.couchdb.org/draft/security.html
http://docs.couchdb.org/en/1.6.1/config/intro.html

**Comment by gr2m** [comment]
I’d suggest we create a new repository `hoodie-app-something-tracker` and make it the default app (template) when creating a new Hoodie app, and deprecate my first hoodie. That will make things more clear and easier to create more template apps in future.

Kind of what we planned here: https://github.com/gr2m/milestones/issues/32, just without the `-template` part, as the app can be used as is, it will be just _used_ as template

**Comment by gr2m** [comment]
closing this in favor of https://github.com/hoodiehq/hoodie-app-something-tracker, please send your PRs to this repo now :)

**Pull request closed without merging**
