### PR TITLE
ARIA roles & HTML semantics for a more accessible experience

### PR DESCRIPTION
**Pull request by Charlotteis**
Hello! I am here to deliver some lovely accessibility to my-first-hoodie!

* 0389ffc: adds a language attribute to the app, so a screenreader knows what pronunciation to use when reading it out loud
* 92399e5: turns the main header `div` into an actual `header` element and adds the appropriate `banner` aria `role`
* b80eec3: adds an aria role of "main" to the main content. Ideally I would have changed the `div` to a `main` element, but this is not supported by IE.
* b828e01: I have set the code block to be contained in an `aside` element because I do not believe this counts as main content, I've also added the `complementary` aria role.
* acf11e3: adds the correct aria role to the footer
* c02152d: adds a hidden label linked to the todo input box, so VoiceOver reads a better explanation of what it does (also, all form elements should have labels to be good valid HTML)
* 6af3a64: fixes a typo within a code comment

I've done a series of small commits, so if anyone doesn't agree with one of them I can take it out easily :)

There are a couple of more complex things I'd like to do in future PRs like letting the user know that they have successfully submitted/finished/deleted their todo, perhaps with use of [ARIA live regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions).

### CODE REVIEW

**Comment by Charlotteis** [comment]
I hope I got the commit messages right, @gr2m :dancer:

**Comment by gr2m** [comment]
you're a commit super :star2:

**Comment by gr2m** [comment]
you just won the price for the best explained PR in Hoodie History :tada: 

Looks all good to me :+1:

**Comment by gr2m** [comment]
merged via d337367

**Comment by boennemann** [comment]
@Charlotteis Thanks for all of this :tada: 

Your explanations are so good that we should ingrain them into the history of this project :)
I don't know what you're using for git, but let's suppose it's the command line:

Instead of doing `git commit -m "the message"` you can just do `git commit`, which then opens your [editor of choice](https://stackoverflow.com/questions/2596805/how-do-i-make-git-use-the-editor-of-my-choice-for-commits), which again makes it easy to enter the summaries you're using now as the first line and the entire explanation right below that as the commit message body. Here is [an example](https://github.com/boennemann/semantic-release/commit/4821aff69eb9d6d79937b0a8e03eec8835faa29e) of what that looks like.

Thanks :sparkling_heart:

**Comment by Charlotteis** [comment]
@boennemann Thanks!

I do actually use [Gitx](http://rowanj.github.io/gitx/) sometimes if I want to do longer commit messages (it's also just a great GUI for git), though primarily I use the command line. I try not to write messages that are too long because I know some people frown upon them. I will endeavour to do longer explanations where needed, particularly for accessibility stuff! :tada:

**Pull request closed without merging**
